spring:
  profiles: cloud

logging:
  level:
    com.example.tutorial: DEBUG
    org.springframework: WARN

# queue service related
rabbitmq:
  username: xxx
  password: xxx
  host: rabbitmq-mgnt.system.prod.cf5.onsclofo.uk
  port: 6672
  virtualhost: /
  # When using publisher confirms, the cache size needs to be large enough otherwise channels can be closed before confirms are received.
  channelCacheSize: 100